#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define USE_KEYBOARD_ELSE_GAMEPAD 1

#if USE_KEYBOARD_ELSE_GAMEPAD == 1
#	define USE_KEYBOARD_FOR_MOVING
#else
#	define USE_GAMEPAD_FOR_MOVING
#endif

#endif